site_name: Elena's Documentation

theme:
  name: 'material'
  font: 
    text: Inter
  font-size:
    text: 9px
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: 'pink'
      accent: 'purple'
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: 'teal'
      accent: 'cyan'
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# Page tree
nav:
  - Home:
    - Build your documentation: Introduction/intro.md

  - Dummies:
    - General: Dummies/GeneralCommands.md
    - CMSSW: Dummies/CMSSWCommands.md
    - Git: Dummies/GitCommands.md
  - NGT:
    - HLT Tutorial: NGT/General/HLTTutorial.md
    - Phase 2 HLT Menu: NGT/Phase2Menu/GettingStarted.md
    - The Optimizer: 
      - Getting started: NGT/PixelPatatrack/TheOptimizer/GettingStarted.md
      - Running the optimization: NGT/PixelPatatrack/TheOptimizer/Running.md